name           = "GIFT"
version        = "3.3.14"
defaultTargets = ["GIFT"]
keywords       = ["mathematics", "physics", "G2", "E8", "holonomy"]

[leanOptions]
pp.unicode.fun          = true
autoImplicit            = false
relaxedAutoImplicit     = false
linter.unnecessarySimpa = false

[[require]]
name = "mathlib"
git  = "https://github.com/leanprover-community/mathlib4.git"
rev  = "v4.27.0"

[[require]]
name = "checkdecls"
git  = "https://github.com/PatrickMassot/checkdecls.git"
rev  = "master"

[[require]]
name = "«doc-gen4»"
git  = "https://github.com/leanprover/doc-gen4"
rev  = "v4.27.0"

[[lean_lib]]
name = "GIFT"
globs = ["GIFT.+"]
